# Generated by Django 2.2 on 2021-03-18 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_Kategori', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Daftarpenjual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_toko', models.CharField(max_length=255)),
                ('keterangan', models.CharField(max_length=255)),
                ('no_hp', models.CharField(max_length=15)),
                ('foto_toko', models.ImageField(blank=True, upload_to='toko/')),
            ],
        ),
        migrations.CreateModel(
            name='Registrasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.CharField(max_length=255)),
                ('harga', models.CharField(max_length=15)),
                ('tanggal', models.DateField(auto_now_add=True, null=True)),
                ('foto', models.ImageField(blank=True, upload_to='produk/')),
                ('kategori', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cats', to='market.Category')),
                ('penjual', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='info', to='market.Daftarpenjual')),
            ],
        ),
    ]
