# Generated by Django 2.2 on 2021-03-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='daftarpenjual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_toko', models.CharField(max_length=255)),
                ('keterangan', models.CharField(max_length=255)),
                ('no_hp', models.CharField(max_length=15)),
                ('foto_toko', models.ImageField(blank=True, upload_to='toko/')),
            ],
        ),
        migrations.CreateModel(
            name='Registrasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kategori', models.CharField(choices=[(None, 'kategori produk'), ('bahan', 'bahan baku'), ('kerajinan', 'kerajinan'), ('jasa', 'jasa'), ('kuliner', 'kuliner siap saji')], default='', max_length=40)),
                ('deskripsi', models.CharField(max_length=255)),
                ('harga', models.CharField(max_length=15)),
                ('no_tlp', models.CharField(max_length=15)),
                ('tanggal', models.DateField(auto_now_add=True, null=True)),
                ('foto', models.ImageField(blank=True, upload_to='produk/')),
            ],
        ),
    ]
