# Generated by Django 2.2 on 2021-03-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrasi',
            name='kategori',
            field=models.CharField(choices=[(None, 'Pilih Kategori'), ('Bahan Baku', 'Bahan Baku'), ('Jasa', 'Jasa'), ('Kuliner', 'Kuliner'), ('Kerajinan', 'Kerajinan')], default='', max_length=40),
        ),
    ]
