# Generated by Django 2.2 on 2021-03-18 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_registrasi_penjual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrasi',
            name='penjual',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='info', to='market.Daftarpenjual'),
        ),
    ]
