# Generated by Django 2.2 on 2021-03-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20210310_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrasi',
            name='foto',
            field=models.ImageField(blank=True, upload_to='produk/'),
        ),
        migrations.AddField(
            model_name='registrasi',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
