# Generated by Django 2.2 on 2021-03-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20210310_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrasi',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
