# Generated by Django 2.2 on 2021-03-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20210311_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrasi',
            name='foto',
            field=models.ImageField(blank=True, upload_to='produk/'),
        ),
    ]
