# Generated by Django 2.2 on 2021-03-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20210311_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrasi',
            name='kategori',
            field=models.CharField(choices=[(None, 'kategori produk'), ('bahan', 'bahan baku'), ('kerajinan', 'kerajinan'), ('jasa', 'jasa'), ('kuliner', 'kuliner siap saji')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='registrasi',
            name='tanggal',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
