# Generated by Django 2.2 on 2021-03-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20210316_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrasi',
            name='penjual',
            field=models.CharField(choices=[(None, 'nama penjual'), ('a', 'a'), ('b', 'b'), ('c', 'c')], default='', max_length=40),
        ),
    ]
