# Generated by Django 2.2 on 2021-03-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_registrasi_penjual'),
    ]

    operations = [
        migrations.CreateModel(
            name='daftarpenjual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_toko', models.CharField(max_length=255)),
                ('keterangan', models.CharField(max_length=255)),
                ('no_hp', models.CharField(max_length=15)),
                ('foto_toko', models.ImageField(blank=True, upload_to='toko/')),
            ],
        ),
    ]
