# Generated by Django 2.2 on 2021-04-30 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_Kategori', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tambahproduk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.CharField(max_length=255)),
                ('harga', models.CharField(max_length=15)),
                ('tanggal', models.DateField(auto_now_add=True, null=True)),
                ('foto', models.ImageField(blank=True, upload_to='produk/')),
                ('kategori', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cats', to='umkmmanagement.Category')),
            ],
        ),
    ]
