# Generated by Django 2.2 on 2021-05-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='foto_Kategori',
            field=models.ImageField(blank=True, upload_to='kategori/'),
        ),
    ]
